<?php
use MetaPlayer\Model\SocialNetwork;
$socialNetwork = $objects['socialNetwork'];
/** @var $socialNetwork \MetaPlayer\Model\SocialNetwork  */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>MetaPlayer - Demo 2 Version</title>
    <link rel="stylesheet" type="text/css" href="/css/mp.css">
    <link rel="stylesheet" type="text/css" href="/css/themes/default/easyui.css">
    <link rel="stylesheet" type="text/css" href="/css/themes/icon.css">
    <link rel="stylesheet" type="text/css" href="/css/blue.monday/jplayer.blue.monday.css" />

    <?php if ($socialNetwork == SocialNetwork::$VK): ?>
    <script type="text/javascript" src="http://vk.com/js/api/xd_connection.js?2"></script>
    <script type="text/javascript" src="/js/vkutils.js"></script>
    <?php elseif ($socialNetwork == SocialNetwork::$MY): ?>
    <script type="text/javascript" src="http://cdn.connect.mail.ru/js/loader.js"></script>
    <script type="text/javascript" src="/js/myutils.js"></script>
    <?php endif; ?>

    <script type="text/javascript" src="/js/jPaq-1.0.6.full.js"></script>
    <script type="text/javascript" src="/js/jquery-1.6.2.js"></script>
    <script type="text/javascript" src="/js/jquery.jplayer.min.js"></script>
    <script type="text/javascript" src="/js/jquery.dateFormat-1.0.js"></script>
    <script type="text/javascript" src="/js/easyloader.js"></script>
    <script type="text/javascript" src="/js/jquery.json-2.3.js"></script>
    <script type="text/javascript" src="/js/jquery.blockUI.js"></script>

    <script type="text/javascript" src="/js/loading.js"></script>

</head>
<body>
<div id="mainHeader">
</div>

<div id="mainBody" class="easyui-layout" style="width: 650px; height: 540px;">
    <div id="bodyTree" region="south" title="Каталог" split="true" style="height: 400px;">
        <div id="bodyAccordion" class="easyui-accordion" style="height: 367px;">
            <div id="treeAccordion" selected="true" title="MetaTree">
                <table id="metaTree" style="height: 288px"
                       class="easyui-treegrid"
                       nowrap="true" rownumbers="false" animate="true" singleSelect="false"
                       idField="id" treeField="name">
                </table>
            </div>
            <div id="playlistAccordion" title="Плейлист">
                <table id="playlist" class="easyui-datagrid" style="height: 288px"
                       singleSelect="true" animate="true" rownumbers="true"
                       idField="id">
                </table>
            </div>
            <div id="editTreeAccordion" title="Пополнить">
                <form id="editTreeForm" action="" method="post">
                    <table>
                        <tr valign="top">
                            <td align="right">
                                <label for="editTypeBand">Группа</label>
                                <input type="radio" id="editTypeBand" name="editType" value="band" checked="checked" onchange="editTypeChanged(this);" onclick="editTypeChanged(this);">
                            </td>
                            <td>
                                <table>
                                    <tr>
                                        <td align="right" valign="top" style="min-width: 100px">Название:</td>
                                        <td id="editCellBandList">
                                            <div id="editDivBandList">
                                                <select id="bandList" style="width: 200px" name="bandList" class="easyui-combobox" validType="checkSelected['band',bandList]" valueField="id" textField="name" mode="local" required="true" missingMessage="Выберите или введите название группы."></select>
                                            </div>
                                            <div id="editDivBandSearch">
                                                <select id="bandSearch" style="width: 200px" name="bandList" class="easyui-combobox" valueField="id" textField="name" required="true" missingMessage="Введите название группы."></select>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td align="right">Дата основания:</td>
                                        <td><input type="text" id="bandFoundDate" name="foundDate" required="true"></td>
                                    </tr>
                                    <tr>
                                        <td align="right">Дата распада:</td>
                                        <td><input type="text" id="bandEndDate" name="endDate"></td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                        <tr valign="top" id="editRowAlbum">
                            <td align="right">
                                <label for="editTypeAlbum">Альбом</label>
                                <input id="editTypeAlbum" type="radio" name="editType" value="album" onchange="editTypeChanged(this);" onclick="editTypeChanged(this);">
                            </td>
                            <td id="editCellAlbum">
                                <table>
                                    <tr>
                                        <td align="right" valign="top" style="min-width: 100px">Название:</td>
                                        <td id="editCellAlbumList">
                                            <div id="editDivAlbumList">
                                                <select name="albumList" style="width: 200px" id="albumList" class="easyui-combobox" validType="checkSelected['album',albumList]" valueField="id" textField="title" mode="local" required="true" missingMessage="Выберите или введите название альбома."></select>
                                            </div>
                                            <div id="editDivAlbumSearch">
                                                <select name="albumSearch" style="width: 200px" id="albumSearch" class="easyui-combobox" valueField="id" textField="title" mode="local" required="true" missingMessage="Введите название альбома."></select><br />
                                                <input type="checkbox" id="editLoadTracks" alt="Загрузить все композиции альбома." checked="true" disabled="true"><label for="editLoadTracks">Загрузить все композиции альбома.</label>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td align="right">Дата выпуска:</td>
                                        <td><input type="text" id="albumReleaseDate" name="releaseDate" required="true"></td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                        <tr valign="top" id="editRowTrack">
                            <td align="right">
                                <label for="editTypeTrack">Композиция</label>
                                <input id="editTypeTrack" type="radio" name="editType" value="track" onchange="editTypeChanged(this);" onclick="editTypeChanged(this);">
                            </td>
                            <td id="editCellTrack">
                                <table>
                                    <tr>
                                        <td align="right" style="min-width: 100px">Название:</td>
                                        <td id="editCellTrackList">
                                            <div id="editDivTrackList">
                                                <input type="text" name="trackList" id="trackList" class="easyui-validatebox" required="true">
                                            </div>
                                            <div id="editDivTrackSearch">
                                                <select name="trackSearch" style="width: 200px" id="trackSearch" class="easyui-combobox" valueField="id" textField="title" mode="local" required="true" missingMessage="Введите название композиции."></select>
                                            </div>
<!--                                                    <select name="trackList" id="trackList" class="easyui-combobox" validType="checkSelected['track',trackList]" valueField="id" textField="title" mode="local" required="true" missingMessage="Выберите или введите название композиции."></select> -->
                                        </td>
                                    </tr>
                                    <tr>
                                        <td align="right">Длит.:</td>
                                        <td>
                                            <input type="text" name="trackDurationMM" id="trackDurationMM" size="2" maxlength="3" class="easyui-numberspinner" required="true" min="0" max="999" value="0" editable="true">:
                                            <input type="text" name="trackDurationSS" id="trackDurationSS" size="2" class="easyui-numberspinner" required="true" min="1" value="0" max="60" editable="true">
                                            <input type="hidden" name="trackDuration" id="trackDuration">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td align="right">Порядк. №:</td>
                                        <td><input type="text" name="trackSerial" id="trackSerial" size="3" class="easyui-numberspinner" min="1" value="1" required="true" missingMessage="Укажите порядковый номер композиции в альбоме."></td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                        <tr>
                            <td align="right">Источник:</td>
                            <td><input type="text" name="editSource" id="editSource" class="easyui-validatebox" required="true" missingMessage="Укажите источник информации (адрес сайта, название книги и т.п.)"></td>
                        </tr>
                        <tr>
                            <td colspan="2">
                                <div id="editMessages"></div>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2"><input id="editSubmit" type="button" name="submit" onclick="$('#editTreeForm').submit();" value="Добавить"></td>
                        </tr>
                    </table>
                </form>
                <div id="hiddenFormElements" style="display: none">
                </div>
            </div>
        </div>
        <div id="treeMenu" class="easyui-menu" style="width:120px;">
            <div onclick="mainTree.playMenuNode()"><b>Проигрывать</b></div>
            <div onclick="">Добавить</div>
            <div class="menu-sep"></div>
            <div id="treeMenuEdit">
                <span>Править</span>
                <div style="width: 120px">
                    <div iconCls="icon-edit" onclick="mainTree.editMenuNode()">Править</div>
                    <div class="menu-sep"></div>
                    <div iconCls="icon-remove" onclick="mainTree.removeMenuNode()">Удалить</div>
                </div>
            </div>
            <div iconCls="icon-reload" onclick="mainTree.reloadMenuNode()">Перегрузить</div>
        </div>
    </div>

    <!-- onclick="mainTree.removeNode('a')" -->
    <div id="bodyPlayer" region="center" title="Плеер" style="height: 140px">
        <div id="mainPlayer" class="jp-jplayer"></div>
        <div id="jp_container_1" class="jp-audio" style="margin: auto">
            <div class="jp-type-playlist">
                <div class="jp-gui jp-interface">
                    <ul class="jp-controls">
                        <li><a href="javascript:;" class="jp-previous" tabindex="1">previous</a></li>
                        <li><a href="javascript:;" class="jp-play" tabindex="1">play</a></li>
                        <li><a href="javascript:;" class="jp-pause" tabindex="1">pause</a></li>
                        <li><a href="javascript:;" class="jp-next" tabindex="1">next</a></li>
                        <li><a href="javascript:;" class="jp-stop" tabindex="1">stop</a></li>
                        <li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute">mute</a></li>
                        <li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">unmute</a></li>
                        <li><a href="javascript:;" class="jp-volume-max" tabindex="1" title="max volume">max volume</a></li>
                    </ul>
                    <div class="jp-progress">
                        <div class="jp-seek-bar">
                            <div class="jp-play-bar"></div>
                        </div>
                    </div>
                    <div class="jp-volume-bar">
                        <div class="jp-volume-bar-value"></div>
                    </div>
                    <div class="jp-time-holder">
                        <div class="jp-current-time"></div>
                        <div class="jp-duration"></div>
                        <!--                                <ul class="jp-toggles">
                            <li><a href="javascript:;" class="jp-repeat" tabindex="1" title="repeat">repeat</a></li>
                            <li><a href="javascript:;" class="jp-repeat-off" tabindex="1" title="repeat off">repeat off</a></li>
                        </ul>-->
                    </div>
                </div>
                <div class="jp-title">
                    <ul>
                        <li>Bubble</li>
                    </ul>
                </div>
                <div class="jp-no-solution">
                    <span>Update Required</span>
                    To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
                </div>
            </div>
        </div>
    </div>
</div>

<?php if ($socialNetwork == SocialNetwork::$VK): ?>

<div id="vk_comments"></div>
<div id="vk_groups"></div>

<?php endif; ?>


<div id="mainFooter" style="float: left; width: 650px; font-size: 11px; font-family: tahoma, arial, verdana, sans-serif, 'Lucida Sans';text-align: center;">
    Для реализации MetaPlayer были использованы:<br />
    <a href="http://marcelog.github.com/Ding/" target="_blank">Ding Framework</a>, special thanks to <a href="mailto://marcelog@gmail.com" target="_blank">Marcelo Gornstein</a>;
    <a href="http://www.doctrine-project.org/" target="_blank">doctrine</a>;
    <a href="http://www.jeasyui.com/" target="_blank">jQuery EasyUI</a>;
    <a href="http://jplayer.org/">jPlayer</a>;<a href="http://musicbrainz.org" target="_blank">the catalogue MusicBrainz</a><br />
    MetaPlayer (c) by Oak Software 2011<br />
</div>
</body>
</html>
