<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title><?= MPConfig::$ProjectName?> - <?= MPConfig::$VersionName;?> Version</title>
        <link rel="stylesheet" type="text/css" href="css/mp.css">
    </head>
    <body>
        К сожалению данный ресурс доступен только <br />
        через социальную сеть <a href="http://vk.com/app<?= \MPConfig::$VKAppId?>">ВКонтакте</a>или<br />
        через социальную сеть <a href="http://my.mail.ru/app<?= \MPConfig::$MyAppId?>">Мой Мои</a><br />
        В будущем планируется перенос на другие платформы.
    </body>
</html>