<?php

namespace MetaPlayer\Model;

require_once dirname(__FILE__) . '/../../../../src/MetaPlayer/Model/Album.php';

/**
 * Test class for Album.
 * Generated by PHPUnit on 2011-12-07 at 21:37:02.
 */
class AlbumTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Album
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Album;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
