<?php

namespace MetaPlayer\Model;

/**
 * Test class for Album.
 * Generated by PHPUnit on 2011-12-07 at 21:37:02.
 * @Component(name=albumTest)
 */
class AlbumTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @Resource
     * @var Ding\Container\IContainer
     */
    private $container;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     *
     */
    public function testTest() {
        $em = $this->container->getBean("em");
    }

}

?>
