<?php

namespace MetaPlayer\Model;

use MetaPlayer\Repository\AlbumRepository;

/**
 * Test class for Album.
 * Generated by PHPUnit on 2011-12-07 at 21:37:02.
 */
class AlbumTest extends \MetaPlayer\BaseTest
{
    /**
     * @var \Doctrine\ORM\EntityManager
     */
    private $entityManager;

    /**
     * @var \Doctrine\DBAL\Connection
     */
    private $connection;
    
    /**
     *
     * @var AlbumRepository
     */
    private $albumRepository;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        parent::setUp();

        $this->entityManager = $this->container->getBean("em");
        $this->albumRepository = $this->container->getBean("albumRepository");
        
        $this->connection = $this->entityManager->getConnection();
        $this->connection->beginTransaction();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        $this->connection->rollback();
    }

    /**
     *
     */
    public function testTest() {
        self::assertNotNull($this->entityManager);

        $band = new Band("test", new \DateTime());
        $this->entityManager->persist($band);
        $this->entityManager->flush();
        self::assertNotNull($band->getId());
        echo $band->getId();

        $album = new Album($band, "test", new \DateTime());
        $this->entityManager->persist($album);
        $this->entityManager->flush();
        self::assertNotNull($album->getId());
    }
    
    public function testGetByBand() {
        $albums = $this->albumRepository->findByBand(1);
        self::assertNotEmpty($albums);
        
        $album = current($albums);
        /* @var $album Album */
        
        self::assertNotNull($album);
        
        $band = $album->getBand();
        self::assertNotNull($band);
        
        self::assertInstanceOf('\DateTime', $album->getReleaseDate());
        
        $albums2 = $this->albumRepository->findByBand($band);
        self::assertNotEmpty($albums2);
    }

}
